version: "3.9"

services:
  backend:
    build: .
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 2004
      MYSQL_DATABASE: tienda_online
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/initdb:/docker-entrypoint-initdb.d

volumes:
  mysql_data: