"""initial

Revision ID: be0b61539948
Revises: 
Create Date: 2025-07-03 03:06:59.636381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0b61539948'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atributos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('tienda_id', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('cliente', 'admin', 'empleado', name='rol_enum'), nullable=False),
    sa.Column('verificado', sa.Boolean(), nullable=True),
    sa.Column('tienda_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tienda_id'], ['tiendas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('admins',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nivel_acceso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('clientes',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('direccion_envio', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('empleados',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('puesto', sa.String(length=30), nullable=True),
    sa.Column('fecha_contratacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagenes_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intentos_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('exito', sa.Boolean(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valores_producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('atributo_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['atributo_id'], ['atributos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestamos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('plazo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobado', 'rechazado', 'pagado', name='estado_prestamo_enum'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reportes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('generado_por', sa.Integer(), nullable=True),
    sa.Column('formato', sa.Enum('PDF', 'CSV', 'XLSX', name='formato_enum'), nullable=False),
    sa.Column('generado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['generado_por'], ['admins.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.Enum('efectivo', 'tarjeta', 'transferencia', name='metodo_pago_enum'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'pagado', 'cancelado', name='estado_venta_enum'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalles_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalles_venta')
    op.drop_table('wishlist')
    op.drop_table('ventas')
    op.drop_table('reportes')
    op.drop_table('prestamos')
    op.drop_table('gastos')
    op.drop_table('carrito')
    op.drop_table('valores_producto')
    op.drop_table('intentos_login')
    op.drop_table('imagenes_producto')
    op.drop_table('eventos')
    op.drop_table('empleados')
    op.drop_table('clientes')
    op.drop_table('admins')
    op.drop_table('usuarios')
    op.drop_table('productos')
    op.drop_table('tiendas')
    op.drop_table('categorias')
    op.drop_table('atributos')
    # ### end Alembic commands ###
